<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MPegawaiTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        \DB::table('m_pegawai')->insertOrIgnore(array (
            0 =>
            array (
                'id_pegawai' => 1,
                'email' => 'saniman@bps.go.id',
                'password' => NULL,
                'nama' => 'Saniman SH',
                'nip_lama' => '340012313',
                'nip' => '196911261989031001',
                'golongan' => 'III',
                'role' => 'user',
                'foto_url' => 'https://community.bps.go.id/images/avatar/12313.JPG',
                'satker' => 'Bagian Umum',
                'kd_satker' => '3300',
            ),
            1 =>
            array (
                'id_pegawai' => 2,
                'email' => 'yuli.purwita@bps.go.id',
                'password' => NULL,
                'nama' => 'Yuli Purwitasari SST',
                'nip_lama' => '340050277',
                'nip' => '198707082009022002',
                'golongan' => 'I',
                'role' => 'admin',
                'foto_url' => 'https://community.bps.go.id/images/avatar/340050277_20170519103616.jpg',
                'satker' => 'BPS Provinsi',
                'kd_satker' => '3300',
            ),
            2 =>
            array (
                'id_pegawai' => 3,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Didik Nursetyohadi M.Agb.',
                'nip_lama' => '340015979',
                'nip' => '197509161999121001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            3 =>
            array (
                'id_pegawai' => 4,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Dr. Dewi Novita Sari SST, M.Stat',
                'nip_lama' => '340016269',
                'nip' => '197908312000122002',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            4 =>
            array (
                'id_pegawai' => 5,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'A\'idzin SE., M.A., M.Eng.',
                'nip_lama' => '340015968',
                'nip' => '197711271999121001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            5 =>
            array (
                'id_pegawai' => 6,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Dra. Eny Pramudyastuti',
                'nip_lama' => '340014463',
                'nip' => '196902241994022001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            6 =>
            array (
                'id_pegawai' => 7,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Mathius Samuharwadi SST',
                'nip_lama' => '340014616',
                'nip' => '196909031994031006',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            7 =>
            array (
                'id_pegawai' => 8,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Irma Nur Afifah SST.,M.Si',
                'nip_lama' => '340015904',
                'nip' => '197512011999032003',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            8 =>
            array (
                'id_pegawai' => 9,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Rezha Nursina Yuni SST',
                'nip_lama' => '340056878',
                'nip' => '199106112014102003',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            9 =>
            array (
                'id_pegawai' => 10,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'A. Noor Taqiyah Zamania SST',
                'nip_lama' => '340056968',
                'nip' => '199111042014122001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            10 =>
            array (
                'id_pegawai' => 11,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Asy-Syifa Hanum Farida SST',
                'nip_lama' => '340058165',
                'nip' => '199503132018022001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            11 =>
            array (
                'id_pegawai' => 12,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Maharanny Diwid Prasetyawati SST, M.Sc.',
                'nip_lama' => '340056354',
                'nip' => '199006052013112001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            12 =>
            array (
                'id_pegawai' => 13,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Buyung Firmansyah SST',
                'nip_lama' => '340056232',
                'nip' => '199002252013111001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            13 =>
            array (
                'id_pegawai' => 14,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Moh. Muhriz Alhakim SST',
                'nip_lama' => '340058360',
                'nip' => '199601192018021001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            14 =>
            array (
                'id_pegawai' => 15,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Joko Mulyono',
                'nip_lama' => '340014621',
                'nip' => '197405141994031003',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            15 =>
            array (
                'id_pegawai' => 16,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Danisworo S.Si, M.Si',
                'nip_lama' => '340015747',
                'nip' => '197706101999011001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            16 =>
            array (
                'id_pegawai' => 17,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Netri Dewantari S.ST, M.Ec.Dev.',
                'nip_lama' => '340053329',
                'nip' => '198706122009122004',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            17 =>
            array (
                'id_pegawai' => 18,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Yusuf Isnandar',
                'nip_lama' => '340013786',
                'nip' => '197105101993121001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            18 =>
            array (
                'id_pegawai' => 19,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Fauziyah Selowati S.Si',
                'nip_lama' => '340018852',
                'nip' => '198109272006042021',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            19 =>
            array (
                'id_pegawai' => 20,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Meryanti Sri Wulandari SST, M.Si.',
                'nip_lama' => '340016250',
                'nip' => '197903062000122002',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            20 =>
            array (
                'id_pegawai' => 21,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Rina Lusiana Handayanti S.AP., M.Sc.',
                'nip_lama' => '340051296',
                'nip' => '198704302009022005',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            21 =>
            array (
                'id_pegawai' => 22,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Budhi Listyarayani S.Si., M.M.',
                'nip_lama' => '340051067',
                'nip' => '198207232009022010',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            22 =>
            array (
                'id_pegawai' => 23,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Hendro Deasmaran S.T.',
                'nip_lama' => '340055031',
                'nip' => '198012222011011008',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            23 =>
            array (
                'id_pegawai' => 24,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Sentono Nugroho A.Md',
                'nip_lama' => '340051316',
                'nip' => '198512182009021004',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            24 =>
            array (
                'id_pegawai' => 25,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Sunarto S.E.',
                'nip_lama' => '340053052',
                'nip' => '198211232009111001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            25 =>
            array (
                'id_pegawai' => 26,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Hyas Amaysta Nuning Ridhowati A.Md',
                'nip_lama' => '340051167',
                'nip' => '198605182009022010',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            26 =>
            array (
                'id_pegawai' => 27,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Bambang Yulistriono S.Pt',
                'nip_lama' => '340018281',
                'nip' => '198107252006041005',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            27 =>
            array (
                'id_pegawai' => 28,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Dina Andriana S.Pi',
                'nip_lama' => '340018282',
                'nip' => '198006172006042004',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            28 =>
            array (
                'id_pegawai' => 29,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Fitri Wahyuni A.Md., S.M.',
                'nip_lama' => '340051138',
                'nip' => '198612052009022010',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            29 =>
            array (
                'id_pegawai' => 30,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Istiqomah SST',
                'nip_lama' => '340015623',
                'nip' => '197509231998032001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            30 =>
            array (
                'id_pegawai' => 31,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Hadi Lestiyono SST',
                'nip_lama' => '340054287',
                'nip' => '198607012010121003',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            31 =>
            array (
                'id_pegawai' => 32,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Ika Budi Ambaryanti SE',
                'nip_lama' => '340018560',
                'nip' => '198110052006042035',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            32 =>
            array (
                'id_pegawai' => 33,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Siska Oktaviana Dwi Anggraeni SST., M.Stat.',
                'nip_lama' => '340056457',
                'nip' => '199010042013112001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            33 =>
            array (
                'id_pegawai' => 34,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Ismunarto S.E.',
                'nip_lama' => '340018743',
                'nip' => '197605142006041016',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            34 =>
            array (
                'id_pegawai' => 35,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Puteri Dasa Ratih SST',
                'nip_lama' => '340056401',
                'nip' => '199110212013112001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            35 =>
            array (
                'id_pegawai' => 36,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Tita Kartika S.Tr.Stat.',
                'nip_lama' => '340060339',
                'nip' => '199809242021042001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            36 =>
            array (
                'id_pegawai' => 37,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Iman Teguh Raharto S.Si, M.Si',
                'nip_lama' => '340013350',
                'nip' => '197004101992111001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            37 =>
            array (
                'id_pegawai' => 38,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Medha Wardhany SST, M.Si.',
                'nip_lama' => '340017351',
                'nip' => '198202272004122002',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            38 =>
            array (
                'id_pegawai' => 39,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Sriningsih SST, M.Si',
                'nip_lama' => '340016239',
                'nip' => '197907152000122001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            39 =>
            array (
                'id_pegawai' => 40,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Dina Nur Rahmawati S.ST.',
                'nip_lama' => '340057348',
                'nip' => '199407032016022001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            40 =>
            array (
                'id_pegawai' => 41,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Hermawan Prasetyo SST, MT.',
                'nip_lama' => '340050116',
                'nip' => '198610082009021005',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            41 =>
            array (
                'id_pegawai' => 42,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Dra. Minatus Saniyah',
                'nip_lama' => '340013450',
                'nip' => '196910191992122001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            42 =>
            array (
                'id_pegawai' => 43,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Rina Kartiningrum SST',
                'nip_lama' => '340019190',
                'nip' => '198404202007012006',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            43 =>
            array (
                'id_pegawai' => 44,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Tri Karjono S.Pi',
                'nip_lama' => '340014632',
                'nip' => '197208281994031005',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            44 =>
            array (
                'id_pegawai' => 45,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Adi Susanto SST',
                'nip_lama' => '340015432',
                'nip' => '197304261997031003',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            45 =>
            array (
                'id_pegawai' => 46,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Dian Eka Putri SST',
                'nip_lama' => '340020068',
                'nip' => '198607092008012003',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            46 =>
            array (
                'id_pegawai' => 47,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Erli Widhi Astuti S.Si, M.Si',
                'nip_lama' => '340013740',
                'nip' => '197111181993122001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            47 =>
            array (
                'id_pegawai' => 48,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Lestania Jayanti S.Pt',
                'nip_lama' => '340018259',
                'nip' => '198207082006042002',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            48 =>
            array (
                'id_pegawai' => 49,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Asna Mega Prabandari SST',
                'nip_lama' => '340056926',
                'nip' => '199007302014102001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            49 =>
            array (
                'id_pegawai' => 50,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Herlina SST',
                'nip_lama' => '340015474',
                'nip' => '197606271997122001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            50 =>
            array (
                'id_pegawai' => 51,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Pristiana Diah Ariyantika SST, M.M.',
                'nip_lama' => '340054208',
                'nip' => '198907112010122003',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            51 =>
            array (
                'id_pegawai' => 52,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Al Barkah Triandika S.Si, M.Ec.Dev.',
                'nip_lama' => '340051022',
                'nip' => '198602232009021004',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            52 =>
            array (
                'id_pegawai' => 53,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Mufti Ramadhan SST.,MT',
                'nip_lama' => '340050159',
                'nip' => '198605222009021002',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            53 =>
            array (
                'id_pegawai' => 54,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Eva Dian Widyastutie SST, M.Ec.Dev',
                'nip_lama' => '340053308',
                'nip' => '198706052009122005',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            54 =>
            array (
                'id_pegawai' => 55,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Septyaji Bangun Anargi S.Si',
                'nip_lama' => '340054063',
                'nip' => '198409092010031002',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            55 =>
            array (
                'id_pegawai' => 56,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Adi Prayitno S.Stat.',
                'nip_lama' => '340017725',
                'nip' => '198304222005021003',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            56 =>
            array (
                'id_pegawai' => 57,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Panular Dinu Satomo S.ST, M.Si',
                'nip_lama' => '340017382',
                'nip' => '198206102004121001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            57 =>
            array (
                'id_pegawai' => 58,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Tri Mulyaningsih SST, M.Stat',
                'nip_lama' => '340016077',
                'nip' => '197705282000022001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            58 =>
            array (
                'id_pegawai' => 59,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Dewi Agita Pradaningtyas SST., M.P.W.K.',
                'nip_lama' => '340056246',
                'nip' => '199011182013112001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            59 =>
            array (
                'id_pegawai' => 60,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Wisnu Nurdiyanto SST, MT',
                'nip_lama' => '340017911',
                'nip' => '198306252006021003',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            60 =>
            array (
                'id_pegawai' => 61,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Indah Purnamasari S.E',
                'nip_lama' => '340018263',
                'nip' => '198501252006042001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            61 =>
            array (
                'id_pegawai' => 62,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'One Dwi Endarningtyas S.E., M.Ak.',
                'nip_lama' => '340018266',
                'nip' => '198712022006042002',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            62 =>
            array (
                'id_pegawai' => 63,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Subuh Sukmono Putro SST., M.Ec.Dev',
                'nip_lama' => '340015332',
                'nip' => '197503151996121001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            63 =>
            array (
                'id_pegawai' => 64,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Dwi Agus Wahyu Riyadi A.Md, S.Kom.',
                'nip_lama' => '340056062',
                'nip' => '198805212012121003',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            64 =>
            array (
                'id_pegawai' => 65,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Yun Restianto',
                'nip_lama' => '340018744',
                'nip' => '197406132006041014',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            65 =>
            array (
                'id_pegawai' => 66,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Muhammad Hanief S.Tr.Stat.',
                'nip_lama' => '340063348',
                'nip' => '200108252024121005',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            66 =>
            array (
                'id_pegawai' => 67,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Rizchi Eka Wahyuni S.ST, M.Kom',
                'nip_lama' => '340053222',
                'nip' => '198701042009122002',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            67 =>
            array (
                'id_pegawai' => 68,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Herry Kusmaiwanto S.Si',
                'nip_lama' => '340018283',
                'nip' => '197205242006041002',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            68 =>
            array (
                'id_pegawai' => 69,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Ir. Endang Tri Wahyuningsih MM',
                'nip_lama' => '340012530',
                'nip' => '196509231990032002',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            69 =>
            array (
                'id_pegawai' => 70,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Rizqi Amalia Hanif SST',
                'nip_lama' => '340057570',
                'nip' => '199309202016022001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            70 =>
            array (
                'id_pegawai' => 71,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Nugroho Imam Darodjat SST, M.Si.',
                'nip_lama' => '340015672',
                'nip' => '197710061998031006',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            71 =>
            array (
                'id_pegawai' => 72,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Arjuliwondo S.Si.',
                'nip_lama' => '340011843',
                'nip' => '196507221988021001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            72 =>
            array (
                'id_pegawai' => 73,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Dyah Indah Rahmawati SST',
                'nip_lama' => '340015229',
                'nip' => '197201231996032001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            73 =>
            array (
                'id_pegawai' => 74,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Yayan Arum Wulandari SE, M.M.',
                'nip_lama' => '340016580',
                'nip' => '197901102002122005',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            74 =>
            array (
                'id_pegawai' => 75,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Yopi Ariesia Ulfa SST, M.Si',
                'nip_lama' => '340020024',
                'nip' => '198603292008012002',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            75 =>
            array (
                'id_pegawai' => 76,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Dwi Indriastuti Yulianingsih SST, MM',
                'nip_lama' => '340053337',
                'nip' => '198607022009122004',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            76 =>
            array (
                'id_pegawai' => 77,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Fitra Eka Nurfarid S.Pd.',
                'nip_lama' => '340056063',
                'nip' => '198912242012121002',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            77 =>
            array (
                'id_pegawai' => 78,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Tegar Prasojo SST',
                'nip_lama' => '340056774',
                'nip' => '199105302014101001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            78 =>
            array (
                'id_pegawai' => 79,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Uswatun Khasanah SST',
                'nip_lama' => '340056905',
                'nip' => '199110252014102001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            79 =>
            array (
                'id_pegawai' => 80,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Anis Ariffah Afanin S.Tr.Stat.',
                'nip_lama' => '340059417',
                'nip' => '199605072019122001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            80 =>
            array (
                'id_pegawai' => 81,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Harjo Teguh Ilmiana S.Si, M.M.',
                'nip_lama' => '340015769',
                'nip' => '197603041999011001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            81 =>
            array (
                'id_pegawai' => 82,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Ir. Sri Diastuti M.M',
                'nip_lama' => '340013610',
                'nip' => '196809291993022001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            82 =>
            array (
                'id_pegawai' => 83,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Sumbodo Aji Cahyono S.Si., M.A',
                'nip_lama' => '340015750',
                'nip' => '197703081999011001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            83 =>
            array (
                'id_pegawai' => 84,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Joko Suwarjo S.Si, M.Si',
                'nip_lama' => '340013741',
                'nip' => '197106131993121001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            84 =>
            array (
                'id_pegawai' => 85,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Aning Widiyatmi SE',
                'nip_lama' => '340015664',
                'nip' => '197412171998032004',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            85 =>
            array (
                'id_pegawai' => 86,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Laela Anisatin',
                'nip_lama' => '340020128',
                'nip' => '198803142008012003',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            86 =>
            array (
                'id_pegawai' => 87,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Rizka Argi Putra S.I.Kom',
                'nip_lama' => '340062292',
                'nip' => '199205312023211007',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            87 =>
            array (
                'id_pegawai' => 88,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Dyah Puspita Sari S.E.',
                'nip_lama' => '340017699',
                'nip' => '198302112005022001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            88 =>
            array (
                'id_pegawai' => 89,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Kristiyanto Sambodo SE',
                'nip_lama' => '340018418',
                'nip' => '197805232006041004',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            89 =>
            array (
                'id_pegawai' => 90,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Rina Ambar Sari S.M.',
                'nip_lama' => '340018286',
                'nip' => '198609222006042001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            90 =>
            array (
                'id_pegawai' => 91,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Siti Novilia Indriasari A.Md',
                'nip_lama' => '340051324',
                'nip' => '198411222009022015',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            91 =>
            array (
                'id_pegawai' => 92,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Haryo Swasti Siantoto S.PSi.',
                'nip_lama' => '340053043',
                'nip' => '198305282009111001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            92 =>
            array (
                'id_pegawai' => 93,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Christina Lia Huwae A.Md., S.A.P.',
                'nip_lama' => '340055018',
                'nip' => '198204262011012009',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            93 =>
            array (
                'id_pegawai' => 94,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Ratri Widowati',
                'nip_lama' => '340062905',
                'nip' => '198808312024212004',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            94 =>
            array (
                'id_pegawai' => 95,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Muhamad Sobirin S.Si',
                'nip_lama' => '340016626',
                'nip' => '197806262002121003',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            95 =>
            array (
                'id_pegawai' => 96,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Wiharyati S.H.',
                'nip_lama' => '340055081',
                'nip' => '198403222011012013',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            96 =>
            array (
                'id_pegawai' => 97,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Sisca Agustin Diani Budiman S.Si.',
                'nip_lama' => '340059249',
                'nip' => '199408162019032001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            97 =>
            array (
                'id_pegawai' => 98,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Lestari Utaminingsih SST',
                'nip_lama' => '340016072',
                'nip' => '197710132000022001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            98 =>
            array (
                'id_pegawai' => 99,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Supri Tuti Ekawati SE',
                'nip_lama' => '340014552',
                'nip' => '196901271994032002',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            99 =>
            array (
                'id_pegawai' => 100,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Renny Widyaningrum S.Psi.',
                'nip_lama' => '340055058',
                'nip' => '198709202011012017',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            100 =>
            array (
                'id_pegawai' => 101,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Noor Aisyah',
                'nip_lama' => '340016730',
                'nip' => '198110152002122001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            101 =>
            array (
                'id_pegawai' => 102,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Aulia Rossy Riswandha S.AP.',
                'nip_lama' => '340062763',
                'nip' => '199208042023211016',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            102 =>
            array (
                'id_pegawai' => 103,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Suci Budi Utami SST, M.Si.',
                'nip_lama' => '340016124',
                'nip' => '197811262000122001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            103 =>
            array (
                'id_pegawai' => 104,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Aksiono Nuswantoro SE',
                'nip_lama' => '340014625',
                'nip' => '196806031994031006',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            104 =>
            array (
                'id_pegawai' => 105,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Evy Kusetyaningrum A.Md., SM.',
                'nip_lama' => '340018980',
                'nip' => '198004292006042010',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            105 =>
            array (
                'id_pegawai' => 106,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Tuti Dwijayanti SE',
                'nip_lama' => '340018438',
                'nip' => '198405192006042004',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            106 =>
            array (
                'id_pegawai' => 107,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Lastri S.Ak',
                'nip_lama' => '340051201',
                'nip' => '198606082009022011',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            107 =>
            array (
                'id_pegawai' => 108,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Ayu Rachmawati A.Md., S.M.',
                'nip_lama' => '340051062',
                'nip' => '198605312009022007',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            108 =>
            array (
                'id_pegawai' => 109,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Ganes Mahendrati Yekti S.Ak',
                'nip_lama' => '340017172',
                'nip' => '198105292003122002',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            109 =>
            array (
                'id_pegawai' => 110,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Dody Sofyan A.P.Kb.N.',
                'nip_lama' => '340059938',
                'nip' => '199912202019121002',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            110 =>
            array (
                'id_pegawai' => 111,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Aditya Rizqi Fauzy A.Md.Ak.',
                'nip_lama' => '340062265',
                'nip' => '200107082023021002',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            111 =>
            array (
                'id_pegawai' => 112,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Metty Nurul Romadhona SST., M.Si',
                'nip_lama' => '340020187',
                'nip' => '198605132008012001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            112 =>
            array (
                'id_pegawai' => 113,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Firda Ni\'matul Chusna SE., M.S.Ak',
                'nip_lama' => '340053430',
                'nip' => '198707122010032003',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            113 =>
            array (
                'id_pegawai' => 114,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Destya Winda Kholifah S.Ak.',
                'nip_lama' => '340061240',
                'nip' => '199712192022032021',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            114 =>
            array (
                'id_pegawai' => 115,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Agus Suprianta',
                'nip_lama' => '340014619',
                'nip' => '196908171994031008',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            115 =>
            array (
                'id_pegawai' => 116,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Erlinda S.ST, M.Ec.Dev',
                'nip_lama' => '340053339',
                'nip' => '198702262009122002',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            116 =>
            array (
                'id_pegawai' => 117,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Hendrawan Toni Taruno SST, MA.',
                'nip_lama' => '340017801',
                'nip' => '198304072006021002',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            117 =>
            array (
                'id_pegawai' => 118,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Mira Ayu Isnainy SST',
                'nip_lama' => '340056363',
                'nip' => '199003222013112001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            118 =>
            array (
                'id_pegawai' => 119,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Wiwid Budi Santoso SST',
                'nip_lama' => '340016057',
                'nip' => '197711021999121001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            119 =>
            array (
                'id_pegawai' => 120,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Linggar Farah Hesti A.Md.',
                'nip_lama' => '340055039',
                'nip' => '198903252011012015',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            120 =>
            array (
                'id_pegawai' => 121,
                'email' => 'rizki.dianing@bps.go.id',
                'password' => NULL,
                'nama' => 'Rizki Dianing Wardhani SST',
                'nip_lama' => '340058469',
                'nip' => '199509102018022001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => 'https://community.bps.go.id/images/avatar/340058469.jpg',
                'satker' => 'Bagian Umum',
                'kd_satker' => '3300',
            ),
            121 =>
            array (
                'id_pegawai' => 122,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Dyah Widiyanti A.Md. Bns.',
                'nip_lama' => '340063737',
                'nip' => '199808142025062004',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            122 =>
            array (
                'id_pegawai' => 123,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Siti Rahayu A.Md.Kom.',
                'nip_lama' => '340063955',
                'nip' => '199202222025062002',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            123 =>
            array (
                'id_pegawai' => 124,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Abdul Ghofur',
                'nip_lama' => '340064012',
                'nip' => '198209062025211039',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            124 =>
            array (
                'id_pegawai' => 125,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Aris Setiawan',
                'nip_lama' => '340064259',
                'nip' => '198906182025211062',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            125 =>
            array (
                'id_pegawai' => 126,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Mansur Hidayat',
                'nip_lama' => '340065041',
                'nip' => '198202062025211037',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            126 =>
            array (
                'id_pegawai' => 127,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Muhammad Sodri',
                'nip_lama' => '340065216',
                'nip' => '197901222025211020',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            127 =>
            array (
                'id_pegawai' => 128,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Ari Sudiyana',
                'nip_lama' => '340064242',
                'nip' => '199101202025211033',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            128 =>
            array (
                'id_pegawai' => 129,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Mugiyana SE',
                'nip_lama' => '340014627',
                'nip' => '197312241994031002',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            129 =>
            array (
                'id_pegawai' => 130,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Ma\'rifah Noor Elyah',
                'nip_lama' => '340012639',
                'nip' => '196804151991012002',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            130 =>
            array (
                'id_pegawai' => 131,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Novianto Wijoko',
                'nip_lama' => '340014613',
                'nip' => '196911291994031006',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            131 =>
            array (
                'id_pegawai' => 132,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Ari Susanto A.Md',
                'nip_lama' => '340017697',
                'nip' => '198302212005021002',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            132 =>
            array (
                'id_pegawai' => 133,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Etikawati Datiek Pratiwi A.Md',
                'nip_lama' => '340018554',
                'nip' => '198201282006042015',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            133 =>
            array (
                'id_pegawai' => 134,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Pudyastuti Saptaningsih SE',
                'nip_lama' => '340013585',
                'nip' => '196706141993022001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            134 =>
            array (
                'id_pegawai' => 135,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Fadhila Tsany Nur Rizky SST',
                'nip_lama' => '340057908',
                'nip' => '199401312017012001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
            135 =>
            array (
                'id_pegawai' => 136,
                'email' => NULL,
                'password' => NULL,
                'nama' => 'Minanur Rohman SST',
                'nip_lama' => '340058357',
                'nip' => '199704032018021001',
                'golongan' => NULL,
                'role' => 'user',
                'foto_url' => NULL,
                'satker' => NULL,
                'kd_satker' => NULL,
            ),
        ));


    }
}
