<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TTransaksiTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('t_transaksi')->delete();
        
        \DB::table('t_transaksi')->insert(array (
            0 => 
            array (
                'id_transaksi' => 2,
                'no_surat' => NULL,
                'date' => '2025-09-29',
                'jam_mulai' => NULL,
                'jam_selesai' => '16:04:23',
                'jam_mulai_disetujui' => NULL,
                'jam_selesai_disetujui' => NULL,
                'hari' => 0,
                'submitted_by_NIP' => '196911261989031001',
                'deskripsi' => NULL,
                'uraian' => 'Testing pengajuan lembur',
                'status' => 'approved',
                'submitted_at' => '2026-03-28',
                'approved_at' => '2026-03-29',
                'approver_employee_id' => '196911261989031001',
                'note' => NULL,
                'tujuan_bekerja' => NULL,
                'team_id_tim' => NULL,
                'dokumentasi_id_dokumentasi' => NULL,
                'tim_kode_tim' => 'QrBzgE3O3lEqVPjy',
            ),
            1 => 
            array (
                'id_transaksi' => 3,
                'no_surat' => NULL,
                'date' => '2026-03-29',
                'jam_mulai' => NULL,
                'jam_selesai' => NULL,
                'jam_mulai_disetujui' => NULL,
                'jam_selesai_disetujui' => NULL,
                'hari' => 0,
                'submitted_by_NIP' => '196911261989031001',
                'deskripsi' => NULL,
                'uraian' => 'melakukan debugging pengajuan lembur',
                'status' => 'approved',
                'submitted_at' => '2026-03-29',
                'approved_at' => '2026-03-29',
                'approver_employee_id' => '196911261989031001',
                'note' => NULL,
                'tujuan_bekerja' => NULL,
                'team_id_tim' => NULL,
                'dokumentasi_id_dokumentasi' => NULL,
                'tim_kode_tim' => 'QrBzgE3O3lEqVPjy',
            ),
            2 => 
            array (
                'id_transaksi' => 5,
                'no_surat' => NULL,
                'date' => '2026-04-01',
                'jam_mulai' => '16:01:00',
                'jam_selesai' => '18:01:00',
                'jam_mulai_disetujui' => '16:01:00',
                'jam_selesai_disetujui' => '18:01:00',
                'hari' => 0,
                'submitted_by_NIP' => '196911261989031001',
                'deskripsi' => NULL,
                'uraian' => 'debugging masalah migration',
                'status' => 'approved',
                'submitted_at' => '2026-04-01',
                'approved_at' => '2026-04-01',
                'approver_employee_id' => '196911261989031001',
                'note' => NULL,
                'tujuan_bekerja' => NULL,
                'team_id_tim' => NULL,
                'dokumentasi_id_dokumentasi' => NULL,
                'tim_kode_tim' => 'QrBzgE3O3lEqVPjy',
            ),
            3 => 
            array (
                'id_transaksi' => 15,
                'no_surat' => NULL,
                'date' => '2026-04-05',
                'jam_mulai' => '16:00:00',
                'jam_selesai' => '19:00:00',
                'jam_mulai_disetujui' => NULL,
                'jam_selesai_disetujui' => NULL,
                'hari' => 1,
                'submitted_by_NIP' => '196911261989031001',
                'deskripsi' => NULL,
                'uraian' => 'controller',
                'status' => 'pending',
                'submitted_at' => '2026-04-05',
                'approved_at' => NULL,
                'approver_employee_id' => '197106131993121001',
                'note' => NULL,
                'tujuan_bekerja' => NULL,
                'team_id_tim' => NULL,
                'dokumentasi_id_dokumentasi' => NULL,
                'tim_kode_tim' => 'QrBzgE3O3lEqVPjy',
            ),
            4 => 
            array (
                'id_transaksi' => 31,
                'no_surat' => NULL,
                'date' => '2026-04-06',
                'jam_mulai' => '16:01:00',
                'jam_selesai' => '20:01:00',
                'jam_mulai_disetujui' => '16:01:00',
                'jam_selesai_disetujui' => '19:03:00',
                'hari' => 0,
                'submitted_by_NIP' => '196911261989031001',
                'deskripsi' => NULL,
                'uraian' => 'test alur bisnis',
                'status' => 'approved',
                'submitted_at' => '2026-04-06',
                'approved_at' => '2026-04-06',
                'approver_employee_id' => '196911261989031001',
                'note' => NULL,
                'tujuan_bekerja' => NULL,
                'team_id_tim' => NULL,
                'dokumentasi_id_dokumentasi' => NULL,
                'tim_kode_tim' => 'QrBzgE3O3lEqVPjy',
            ),
            5 => 
            array (
                'id_transaksi' => 32,
                'no_surat' => NULL,
                'date' => '2026-04-04',
                'jam_mulai' => '10:00:00',
                'jam_selesai' => '16:00:00',
                'jam_mulai_disetujui' => '10:00:00',
                'jam_selesai_disetujui' => '14:00:00',
                'hari' => 1,
                'submitted_by_NIP' => '196911261989031001',
                'deskripsi' => NULL,
                'uraian' => 'melakukan pemeriksaan',
                'status' => 'approved',
                'submitted_at' => '2026-04-07',
                'approved_at' => '2026-04-07',
                'approver_employee_id' => '196911261989031001',
                'note' => NULL,
                'tujuan_bekerja' => NULL,
                'team_id_tim' => NULL,
                'dokumentasi_id_dokumentasi' => NULL,
                'tim_kode_tim' => 'QrBzgE3O3lEqVPjy',
            ),
            6 => 
            array (
                'id_transaksi' => 35,
                'no_surat' => NULL,
                'date' => '2026-04-08',
                'jam_mulai' => '16:01:00',
                'jam_selesai' => '17:01:00',
                'jam_mulai_disetujui' => NULL,
                'jam_selesai_disetujui' => NULL,
                'hari' => 0,
                'submitted_by_NIP' => '196911261989031001',
                'deskripsi' => NULL,
                'uraian' => 'coba kurang dari 2 jam',
                'status' => 'rejected',
                'submitted_at' => '2026-04-08',
                'approved_at' => NULL,
                'approver_employee_id' => '196911261989031001',
                'note' => 'Durasi lembur kurang dari 2 jam.',
                'tujuan_bekerja' => NULL,
                'team_id_tim' => NULL,
                'dokumentasi_id_dokumentasi' => NULL,
                'tim_kode_tim' => 'QrBzgE3O3lEqVPjy',
            ),
            7 => 
            array (
                'id_transaksi' => 44,
                'no_surat' => NULL,
                'date' => '2026-04-18',
                'jam_mulai' => '09:00:00',
                'jam_selesai' => '17:00:00',
                'jam_mulai_disetujui' => '09:00:00',
                'jam_selesai_disetujui' => '15:00:00',
                'hari' => 1,
                'submitted_by_NIP' => '196911261989031001',
                'deskripsi' => NULL,
                'uraian' => 'coba lebih dari 6 jam',
                'status' => 'approved',
                'submitted_at' => '2026-04-09',
                'approved_at' => '2026-04-09',
                'approver_employee_id' => '196911261989031001',
                'note' => NULL,
                'tujuan_bekerja' => NULL,
                'team_id_tim' => NULL,
                'dokumentasi_id_dokumentasi' => 2,
                'tim_kode_tim' => 'QrBzgE3O3lEqVPjy',
            ),
            8 => 
            array (
                'id_transaksi' => 45,
                'no_surat' => NULL,
                'date' => '2026-02-04',
                'jam_mulai' => '16:01:00',
                'jam_selesai' => '20:00:00',
                'jam_mulai_disetujui' => '16:01:00',
                'jam_selesai_disetujui' => '16:40:00',
                'hari' => 0,
                'submitted_by_NIP' => '196911261989031001',
                'deskripsi' => NULL,
                'uraian' => 'cobain lah yang mundur',
                'status' => 'approved',
                'submitted_at' => '2026-04-09',
                'approved_at' => '2026-04-09',
                'approver_employee_id' => '196911261989031001',
                'note' => NULL,
                'tujuan_bekerja' => NULL,
                'team_id_tim' => NULL,
                'dokumentasi_id_dokumentasi' => NULL,
                'tim_kode_tim' => 'QrBzgE3O3lEqVPjy',
            ),
            9 => 
            array (
                'id_transaksi' => 46,
                'no_surat' => NULL,
                'date' => '2026-04-20',
                'jam_mulai' => '16:01:00',
                'jam_selesai' => '19:00:00',
                'jam_mulai_disetujui' => '16:01:00',
                'jam_selesai_disetujui' => '17:05:00',
                'hari' => 0,
                'submitted_by_NIP' => '196911261989031001',
                'deskripsi' => NULL,
                'uraian' => 'martabak telor spesial',
                'status' => 'rejected',
                'submitted_at' => '2026-04-09',
                'approved_at' => '2026-04-09',
                'approver_employee_id' => '196911261989031001',
                'note' => 'Durasi lembur kurang dari 2 jam.',
                'tujuan_bekerja' => NULL,
                'team_id_tim' => NULL,
                'dokumentasi_id_dokumentasi' => NULL,
                'tim_kode_tim' => 'QrBzgE3O3lEqVPjy',
            ),
            10 => 
            array (
                'id_transaksi' => 47,
                'no_surat' => NULL,
                'date' => '2026-04-08',
                'jam_mulai' => '16:01:00',
                'jam_selesai' => '17:30:00',
                'jam_mulai_disetujui' => NULL,
                'jam_selesai_disetujui' => NULL,
                'hari' => 0,
                'submitted_by_NIP' => '199509102018022001',
                'deskripsi' => NULL,
                'uraian' => 'jsfddjghk,hgj',
                'status' => 'rejected',
                'submitted_at' => '2026-04-09',
                'approved_at' => NULL,
                'approver_employee_id' => '197106131993121001',
                'note' => 'Durasi lembur kurang dari 2 jam.',
                'tujuan_bekerja' => NULL,
                'team_id_tim' => NULL,
                'dokumentasi_id_dokumentasi' => NULL,
                'tim_kode_tim' => 'QrBzgE3O3lEqVPjy',
            ),
            11 => 
            array (
                'id_transaksi' => 48,
                'no_surat' => NULL,
                'date' => '2026-04-08',
                'jam_mulai' => '16:01:00',
                'jam_selesai' => '23:09:00',
                'jam_mulai_disetujui' => '16:01:00',
                'jam_selesai_disetujui' => '23:09:00',
                'hari' => 0,
                'submitted_by_NIP' => '199509102018022001',
                'deskripsi' => NULL,
                'uraian' => 'jggf',
                'status' => 'approved',
                'submitted_at' => '2026-04-09',
                'approved_at' => '2026-04-09',
                'approver_employee_id' => '196911261989031001',
                'note' => NULL,
                'tujuan_bekerja' => NULL,
                'team_id_tim' => NULL,
                'dokumentasi_id_dokumentasi' => NULL,
                'tim_kode_tim' => 'QrBzgE3O3lEqVPjy',
            ),
        ));
        
        
    }
}